
    
    
    
    
    
    # - docker run -d -p 3000:3000 brownman/docker_rootless; sleep 10
    # - curl --retry 10 --retry-delay 5 -v http://localhost:3000
    
# https://gist.github.com/billhorsman/3605244
#  override:
#    - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
#    - docker build -t $CONTAINER .
#    - mkdir -p ~/docker; docker save $CONTAINER > ~/docker/image.tar
#  - docker info
