# install ruby, bundler
RUN 		wget -qO - https://raw.github.com/fesplugas/rbenv-installer/master/bin/rbenv-installer | bash
ENV 		RBENV_ROOT ${HOME}/.rbenv
ENV 		PATH ${RBENV_ROOT}/bin:${PATH}

RUN 		rbenv install $INSTALL_RUBY_VERSION
RUN 		rbenv global $INSTALL_RUBY_VERSION
RUN 		echo "eval \"\$(rbenv init -)\"" >> $HOME/.profile
RUN         . $HOME/.profile && gem install bundler
